### ISSUE TITLE
Queue is reversed

### ISSUE THREAD

**Issue by moritz157** [joews/rubik-js#3]
The queue of moves to make is unfortunatly reversed. This is caused by the following two actions you are performing on the queue:

**rubik.js**
`var pushMove = function(cube, clickVector, axis, direction) {`
    `moveQueue.push({ cube: cube, vector: clickVector, axis: axis, direction: direction });`
 ` }`

and  (in the same file)
`var startNextMove = function() {`
`    var nextMove = moveQueue.pop();`
`...}`

The problem here is that `moveQueue.push()` adds an element to **the end** of the array but you get the next move by `moveQueue.pop()` which also returns **the last** element of the array. Therefore you are performing the latest move added to the queue instead of the first.

This can be easily solved by using `moveQueue.unshift()` instead of `moveQueue.pop()`

**Comment by joews** [comment]
Whoops! that's a badly-named variable. It should really be `moveStack`, but the `pop` is intentional.
